### Admin Signup
# POST http://localhost:8080/admin/auth/signup
# Content-Type: application/json

# {
#   "firstname": "Hakeem",
#   "lastname": "Bello",
#   "username": "hackhim@22",
#   "password": "StrongPassword123"
# }

POST http://localhost:8080/admin/auth/signin
Content-Type: application/json

{
  "username": "hackhim@22",
  "password": "StrongPassword123"
}

